project_id = "pwjuvfclcltphuuwlsdr"

[functions.chat-ai]
verify_jwt = false

[functions.canvas-generator]
verify_jwt = true

[functions.suggest-squad]
verify_jwt = true

[functions.analytics-track]
verify_jwt = true

[functions.integration-sync]
verify_jwt = true

[functions.market-research]
verify_jwt = false

[functions.generate-persona-image]
verify_jwt = false

[functions.generate-insights]
verify_jwt = true

[functions.generate-daily-missions]
verify_jwt = false